#
# Definition of all trackable objects
# Identifier corresponds to Trackable ID set in Tracking Tools
#
rigid_bodies:
    '0':
        odom: Robot_1/Odom
    '1':
        odom: Robot_2/Odom
nokov_config:
        server_address: "10.1.1.198"
